/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public static void main(String[] args) {
      SAP.main(new String[] {"/home/aitbits/workspace/Java/algs4/WordNet/src/main/java/digraph1.txt"});
    }
}
