/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import edu.princeton.cs.algs4.Digraph;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Digraph a = new Digraph(5);
        String b = new String();
    }
}
