/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public static void main(String[] args) {
      SAP.main(new String[] {"wordnet/digraph1.txt"});
    }
}
